runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  REDIS_ADDR: 130.211.236.141:6379
  REDIS_PASSWORD: yF14Kcdk
  MG_API_KEY: key-472e75a10f6ceb91d70cf3fa89aca2a7
  MG_DOMAIN: mg.phrhero.com
  MG_PUBLIC_API_KEY: pubkey-b1b4cd5ebd95bfc3ef342d072e884c3d
