version: "3"

services:
  shiva-dev:
    image: aum-shiva-dev
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - $GOPATH:/go:ro
      - .:/go/src/github.com/artificial-universe-maker/shiva:ro
    ports:
      - 8000:8080
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    ports:
      - 5432:5432
  adminer:
      image: adminer
      ports:
          - 8001:8080
  redis:
    image: redis
    ports:
      - 6380:6379